# Installs memcached

- name: Install memcached
  apt:
    name: memcached
    state: present
    update_cache: yes
  tags:
    - install
    - install:memcache

- name: add configuration file
  template:
    src: memcached.conf.j2
    dest: /etc/memcached.conf
  tags:
    - install
    - install:memcache
  notify:
    - restart memcache
