---
dependencies:
  - common
  - supervisor
  - edxapp_common
  - nltk
  - role: edx_themes
    themes_user: "{{ edxapp_user }}"
    themes_group: "{{ common_web_group }}"
    when: "{{ EDXAPP_ENABLE_COMPREHENSIVE_THEMING }}"
