---
# Build a kibana/logstash/elasticsearch server for capturing and
# analyzing logs.
- name: Configure syslog server
  hosts: all
  become: True
  roles:
    - common
    - oraclejdk
    - elasticsearch_2
    - logstash_2
    - kibana_4
    - role: nginx
      nginx_sites:
      - kibana_4
